# Generated by Django 5.0.6 on 2024-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('hse_inspector', 'HSE Inspector'), ('project_manager', 'Project Manager')], max_length=20),
        ),
    ]
